export enum PackageState {
  RELABEL_PENDING = 'RELABEL_PENDING',
  READY_TO_DISPATCH = 'READY_TO_DISPATCH',
  DISPATCHED = 'DISPATCHED',
  LASTMILE_EXPIRED = 'LASTMILE_EXPIRED',
  CANCELLED = 'CANCELLED',
}
